package schach.interaction.commands;

import schach.interaction.TestableSession;
import schach.interaction.Session.SessionStatus;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests that AbortGameCommand works correctly.
 */
public class AbortGameCommandTest {
  private AbortGameCommand command = new AbortGameCommand();

  /**
   * Tests that applyTo aborts the current game.
   */
  @Test
  public void testApplyTo() {
    TestableSession session = new TestableSession();
    session.startFake();
    command.applyTo(session);
    assertEquals(SessionStatus.STOPPED, session.getStatus());
  }

  /**
   * Tests that the command is allowed to be generated by an inactive player.
   */
  @Test
  public void testAllowedFromInactivePlayer() {
    assertTrue(command.allowedFromInactivePlayer());
  }
}
